site_name: OUC-HWU Academic Guide
site_description: "OUC-HWU 计科中外项目课程、科研、升学与专业发展知识库"
site_url: https://ouc-hw-survial-guidance.readthedocs.io/zh-cn/latest/
repo_url: https://github.com/zhaorui-bi/OUC-HW-Survial-Guidance
repo_name: zhaorui-bi/OUC-HW-Survial-Guidance
site_author: "Zhaorui(Elijah) JIANG"
copyright: "Copyright &copy; OUC-HWU Survival Guidance Team 2026"

nav:
  - 首页: index.md
  - 专栏篇:
      - 申研规划: 申研规划.md
      - 保研规划: 保研规划.md
      - 机器人学习规划: 机器人学习规划.md
      - AI4Science 学习规划: AI4Science学习规划.md
      - 雅思备考: 雅思备考.md
      - 行前准备: 行前准备.md
      - 留学生做饭菜谱: 留学生做饭菜谱.md
      - 计算物理学: 计算物理学.md
      - Verilog 使用说明: Verilog代码/使用说明.md
  - FAQ: FAQ.md
  - 更新日志: Release_notes.md
  - 使用协议: usage-license.md
  # - Developer guild: Developer_guild.md

plugins:
  - search:
      lang:
        - zh
        - en
  - mkdocs-jupyter
  - glightbox
  # - gen-files:
  #     scripts:
  #       - docs/gen_ref_pages.py
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      # custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: false

theme:
  name: material
  custom_dir: docs/overrides
  logo: img/logo.png
  favicon: img/ico.png

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  #- mkautodoc
  - attr_list
  - md_in_html
  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite

extra_javascript:
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/custom.css
